### ISSUE TITLE
Transfer to jstransformers organization

### ISSUE THREAD

**Issue by RobLoach** [RobLoach/jstransformer-markdown-it#1]
cc @TimothyGu @hemanth

**Comment by TimothyGu** [comment]
Done. I actually just manually did a bare clone and pushed it to jstransformers/jstransformer-markdown-it, but I've added you as a collaborator in that repo so you should be able to push to it.

I also did some fixes in the tests area, and got Travis CI and Coveralls going. I also pushed it to NPM with you, me, and the rest of @jstransformers as maintainers.

Thanks for your work on this!

**Comment by RobLoach** [comment]
:+1:

**Comment by hemanth** [comment]
:+1:
